### PR TITLE
Update and rename test1.txt to test2.txt

### PR DESCRIPTION
**Pull request by stkddks**
hi
bye
dltkddk qkqh ajdcjddl
hul nuemuhe jungmal
i run ne mam mo ru go nuemuhe nuemuhe

### CODE REVIEW

**Comment by jackmin11** [comment]
ok this success

**Comment by dkrl7878** [comment]
야 한국어해라 ㅡㅡ

**Comment by jackmin11** [comment]
no no only English

**Comment by dkrl7878** [comment]
한국어써주세요 센세

**Comment by stkddks** [comment]
hey Korean!! Only use English here!!!

**Pull request merged**
